SomDasAntigasWebApp/Pages/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using SomDasAntigasWebApp.Models;
using SomDasAntigasWebApp.Services;

namespace SomDasAntigasWebApp.Pages;

public class CreateModel : PageModel
{
    public SelectList GenreOptionItems { get; set; }
    private IDiscService _service;
    public CreateModel(IDiscService service)
    {
        _service = service;
    }

    public void OnGet()
    {
        GenreOptionItems = new SelectList(_service.GetAllGenres(),
        nameof(Genre.GenreId),
        nameof(Genre.GenreName));
    }

    [BindProperty]
    public Disc Disc { get; set; }

    public IActionResult OnPost()
    {
        if (!ModelState.IsValid)
        {
            return Page();
        }

        _service.Include(Disc);

        //com o modelo valido, o usuario sera encaminhado para a pag principal
        return RedirectToPage("/Index");
    }
}

SomDasAntigasWebApp/Pages/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SomDasAntigasWebApp.Models;
using SomDasAntigasWebApp.Services;

namespace SomDasAntigasWebApp.Pages
{
    public class DetailsModel : PageModel
    {
        private IDiscService _service;
        public DetailsModel(IDiscService service)
        {
            _service = service;
        }
        public Disc Disc { get; private set; }
        public IActionResult OnGet(int id)
        {
            Disc = _service.Get(id);

            if (Disc == null)
            {
                return NotFound();
            }

            return Page();
        }
    }
}

SomDasAntigasWebApp/Pages/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using SomDasAntigasWebApp.Models;
using SomDasAntigasWebApp.Services;

namespace SomDasAntigasWebApp.Pages;

public class EditModel : PageModel
{
    public SelectList GenreOptionItems { get; set; }

    private IDiscService _service;
    public EditModel(IDiscService service)
    {
        _service = service;
    }

    [BindProperty]
    public Disc Disc { get; set; }

    public IActionResult OnGet(int id)
    {
        Disc = _service.Get(id);

        GenreOptionItems = new SelectList(_service.GetAllGenres(),
nameof(Genre.GenreId),
nameof(Genre.GenreName));

        if (Disc == null)
        {
            return NotFound();
        }

        return Page();
    }

    public IActionResult OnPost()
    {
        if (!ModelState.IsValid)
        {
            return Page();
        }

        _service.Include(Disc);

        //com o modelo valido, o usuario sera encaminhado para a pag principal
        return RedirectToPage("/Index");
    }

    public IActionResult OnPostExclusao()
    {
        _service.Delete(Disc.DiscId);

        return RedirectToPage("/Index");

    }
}

SomDasAntigasWebApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace SomDasAntigasWebApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

SomDasAntigasWebApp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using SomDasAntigasWebApp.Models;
using SomDasAntigasWebApp.Services;

namespace SomDasAntigasWebApp.Pages;

public class IndexModel : PageModel
{
    private IDiscService _service;
    public IndexModel(IDiscService service)
    {
        _service = service;
    }
    public IList<Disc> ListDisc { get; private set; }
    public void OnGet()
    {
        ViewData["Title"] = "Home page";

        ListDisc = _service.GetAll();
    }
}

SomDasAntigasWebApp/Pages/AboutUs.cshtml
@page
@{
    ViewData["Title"] = "Quem Somos";
}
<h1 class="pt-4">@ViewData["Title"]</h1>

<div class="container mt-4">
    <div class="row">
        <div class="col-md-6">
            <p>Somos uma apaixonada equipe de colecionadores de discos de vinil. Nossa loja foi fundada em 1990 e desde então nos dedicamos a oferecer uma ampla seleção de discos de vinil, desde clássicos até edições especiais e raridades. Nosso objetivo é promover a paixão pela música e preservar a experiência única de ouvir discos de vinil.</p>

            <h3>Nossos Valores</h3>
            <ul>
                <li>Qualidade e autenticidade dos produtos</li>
                <li>Atendimento personalizado e especializado</li>
                <li>Promoção da cultura musical e do vinil</li>
                <li>Satisfação do cliente em primeiro lugar</li>
            </ul>
        </div>
        <div class="col-md-6">
            <img src="/images/front_store.jpg" class="img-fluid" alt="Loja de Discos">
            <p class="mt-2">Venha e descubra o prazer de colecionar discos de vinil!</p>
        </div>
    </div>
</div>

SomDasAntigasWebApp/Pages/Create.cshtml
@page
@model CreateModel

<div class="row pt-5">
    <div class="col-md-4">
        <form method="post">
            <h4>Inclusão de Disco</h4>
            <hr />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">

                <label asp-for="Disc.Name" class="control-label"></label>
                <input asp-for="Disc.Name" class="form-control" />
                <span asp-validation-for="Disc.Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Disc.Band" class="control-label"></label>
                <input asp-for="Disc.Band" class="form-control" />
                <span asp-validation-for="Disc.Band" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Disc.Description" class="control-label"></label>
                <input asp-for="Disc.Description" class="form-control" />
                <span asp-validation-for="Disc.Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Disc.ImageUri" class="control-label"></label>
                <input asp-for="Disc.ImageUri" class="form-control" />
                <span asp-validation-for="Disc.ImageUri" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Disc.Price" class="control-label"></label>
                <input asp-for="Disc.Price" class="form-control" />
                <span asp-validation-for="Disc.Price" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Disc.Release" class="control-label"></label>
                <input asp-for="Disc.Release" class="form-control" />
                <span asp-validation-for="Disc.Release" class="text-danger"></span>
            </div>

            <div class="form-group mt-3 mb-3">
                <label asp-for="Disc.GenreId" class="control-label"></label>

                <select class="form-select" asp-for="Disc.GenreId" asp-items="Model.GenreOptionItems">
                    <option value="">Selecione uma opção</option>
                </select>
                <span asp-validation-for="Disc.GenreId" class="text-danger">
                </span>
            </div>

            <div class="form-group mt-4">
                <input type="submit" value="Salvar" class="btn btn-primary" />
             </div>
        </form>
    </div>
</div>

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

}

SomDasAntigasWebApp/Pages/Details.cshtml
@page "/detalhe/{slug}/{id}"
@model SomDasAntigasWebApp.Pages.DetailsModel

<h2 class="my-3">@Model.Disc.Name</h2>
<div class="row">
    <div class="col-4">
        <img class="img-fluid rounded" src="@Model.Disc.ImageUri">
    </div>
    <div class="col-6">
        <h4 class="my-3">Sobre:</h4>
        <p>@Model.Disc.Description</p>
        <h4 class="my-3">Mais Info:</h4>
        <ul>
            <li><label asp-for="Disc.Band"></label>: @Model.Disc.Band</li>
            <li><label asp-for="Disc.Release"></label>: @Model.Disc.Release</li>
            <li><label asp-for="Disc.Price"></label>: @Html.DisplayFor(model => model.Disc.Price)</li>
        </ul>
        @if (User.Identity.IsAuthenticated)
        {
            //Exibir elementos somente para usuários autenticados
            <a class="btn my-3 btn-primary" asp-page="/Edit" asp-route-id="@Model.Disc.DiscId">Editar</a>
        }
        
    </div>
</div>

SomDasAntigasWebApp/Pages/Edit.cshtml
@page
@model SomDasAntigasWebApp.Pages.EditModel

<div class="row pt-5">
    <div class="col-md-4">
        <form method="post">
            <h4>Alteração de Disco</h4>
            <hr />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input type = "hidden" asp-for = "Disc.DiscId" />

            <div class="form-group">

                <label asp-for="Disc.Name" class="control-label"></label>
                <input asp-for="Disc.Name" class="form-control" />
                <span asp-validation-for="Disc.Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Disc.Band" class="control-label"></label>
                <input asp-for="Disc.Band" class="form-control" />
                <span asp-validation-for="Disc.Band" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Disc.Description" class="control-label"></label>
                <input asp-for="Disc.Description" class="form-control" />
                <span asp-validation-for="Disc.Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Disc.ImageUri" class="control-label"></label>
                <input asp-for="Disc.ImageUri" class="form-control" />
                <span asp-validation-for="Disc.ImageUri" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Disc.Price" class="control-label"></label>
                <input asp-for="Disc.Price" class="form-control" />
                <span asp-validation-for="Disc.Price" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Disc.Release" class="control-label"></label>
                <input asp-for="Disc.Release" class="form-control" />
                <span asp-validation-for="Disc.Release" class="text-danger"></span>
            </div>

            <div class="form-group mt-3 mb-3">
                <label asp-for="Disc.GenreId" class="control-label"></label>

                <select class="form-select" asp-for="Disc.GenreId" asp-items="Model.GenreOptionItems">
                    <option value="">Selecione uma opção</option>
                </select>
                <span asp-validation-for="Disc.GenreId" class="text-danger">
                </span>
            </div>

            <div class="form-group mt-4">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                <input type="submit" value="Excluir" class="btn btn-danger" asp-page-handler="Exclusao"/>

            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

}

SomDasAntigasWebApp/Pages/Index.cshtml
@page
@model IndexModel

<div class="row justify-content-md-center">
    @foreach (var item in Model.ListDisc)
    {
        <div class="card col-3 m-3">
            <img src="@item.ImageUri" class="p-3" style="border-radius: 25px">
            <div class="card-body">
                <h5 class="card-title">@item.Name</h5>
                <p class="card-text">@item.Description</p>
                <a class="btn btn-primary" asp-page="/Details" 
                asp-route-slug = "@item.NameSlug"
                asp-route-id ="@item.DiscId">Detalhes</a>
            </div>
        </div>     
    }

</div>

SomDasAntigasWebApp/Pages/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>